name: CICD
 
on:

  workflow_dispatch:
     inputs:
       environments:
         description: This is the environment value where this is workflow is runs
         default: 'dev'
         required: true
         type: choice
         options:
           - dev
           - prod
           - staging
 
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        run: echo "code clone from Github"
 
  build:
    needs : [code]
    runs-on: ubuntu-latest
    steps:
      - name: Build Docker container
        run: echo "Docker container build"
 
  test:
    needs : [build]
    runs-on: ubuntu-latest
    steps:
      - name: Test container
        run: echo "testing container"
 
  deploy:
    needs : [test]
    runs-on: ubuntu-latest
    steps:
      - name: Deploying the app
        run: echo "Docker compose deploy the app"
